import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "../src/components/Header";
import Footer from "../src/components/Footer";
import { SearchProvider } from "@/src/context/SearchContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body style={{
          minHeight: "100vh",
          display: "flex",
          flexDirection: "column",
        }}>
        <SearchProvider>
          <Header />

          <main
            style={{
              paddingTop: "90px",
              flex: 1,
            }}
          >
            {children}
          </main>

          <Footer />
        </SearchProvider>
      </body>
    </html>
  );
}
